import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart Chef",
  description: "Generated by Smart Chef",
  icons:{
    icon:"images/WhatsApp Image 2025-12-31 at 20.52.06.jpeg"
  }
};
export default function StatusLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">    
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-slate-950`}>
      {children}
    </body>
    </html>
  );
}